// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConsoleNorthwind
{

    // Alphabetical list of products
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.31.1.0")]
    public class AlphabeticalListOfProduct
    {
        [Column(@"ProductID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Product ID")]
        public int ProductId { get; set; } // ProductID (Primary key)

        [Column(@"ProductName", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(40)]
        [StringLength(40)]
        [Key]
        [Display(Name = "Product name")]
        public string ProductName { get; set; } // ProductName (Primary key) (length: 40)

        [Display(Name = "Supplier ID")]
        public int? SupplierId { get; set; } // SupplierID

        [Display(Name = "Category ID")]
        public int? CategoryId { get; set; } // CategoryID

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Quantity per unit")]
        public string QuantityPerUnit { get; set; } // QuantityPerUnit (length: 20)

        [Display(Name = "Unit price")]
        public decimal? UnitPrice { get; set; } // UnitPrice

        [Display(Name = "Units in stock")]
        public short? UnitsInStock { get; set; } // UnitsInStock

        [Display(Name = "Units on order")]
        public short? UnitsOnOrder { get; set; } // UnitsOnOrder

        [Display(Name = "Reorder level")]
        public short? ReorderLevel { get; set; } // ReorderLevel

        [Column(@"Discontinued", Order = 10, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Discontinued")]
        public bool Discontinued { get; set; } // Discontinued (Primary key)

        [Column(@"CategoryName", Order = 11, TypeName = "nvarchar")]
        [Required]
        [MaxLength(15)]
        [StringLength(15)]
        [Key]
        [Display(Name = "Category name")]
        public string CategoryName { get; set; } // CategoryName (Primary key) (length: 15)
    }

}
// </auto-generated>
