// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{

    // engineer_order
    [Table("engineer_order", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class EngineerOrder
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"engineer_order_id", Order = 1, TypeName = "int")]
        [Index(@"PK__engineer__FDF15739A771612F", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Engineer order ID")]
        public int EngineerOrderId { get; set; } // engineer_order_id (Primary key)

        [Column(@"engineer_id", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Engineer ID")]
        public int EngineerId { get; set; } // engineer_id

        [Column(@"order_placed", Order = 3, TypeName = "datetime")]
        [Required]
        [Display(Name = "Order placed")]
        public System.DateTime OrderPlaced { get; set; } // order_placed

        // Reverse navigation

        /// <summary>
        /// Child EngineerOrderItems where [engineer_order_item].[engineer_order_id] point to this entity (EOI_FK)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<EngineerOrderItem> EngineerOrderItems { get; set; } // engineer_order_item.EOI_FK

        // Foreign keys

        /// <summary>
        /// Parent Engineer pointed by [engineer_order].([EngineerId]) (EO_FK)
        /// </summary>
        [ForeignKey("EngineerId")] public virtual Engineer Engineer { get; set; } // EO_FK

        public EngineerOrder()
        {
            EngineerOrderItems = new System.Collections.Generic.List<EngineerOrderItem>();
        }
    }

}
// </auto-generated>
