// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{

    // Region
    [Table("Region", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class Region
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"RegionID", Order = 1, TypeName = "int")]
        [Index(@"PK_Region", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Region ID")]
        public int RegionId { get; set; } // RegionID (Primary key)

        [Column(@"RegionDescription", Order = 2, TypeName = "nchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Region description")]
        public string RegionDescription { get; set; } // RegionDescription (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Territories where [Territories].[RegionID] point to this entity (FK_Territories_Region)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Territory> Territories { get; set; } // Territories.FK_Territories_Region

        public Region()
        {
            Territories = new System.Collections.Generic.List<Territory>();
        }
    }

}
// </auto-generated>
