// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{

    // Order Details Extended
    [Table("Order Details Extended", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ViewOrderDetailsExtended /* Column Count = 7 */
    {
        // Number of columns for table ViewOrder Details Extended = 7
        public static int ColumnCount = 7;

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"OrderID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Order ID")]
        public int OrderId { get; set; } // OrderID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductID", Order = 2, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Product ID")]
        public int ProductId { get; set; } // ProductID (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(40)]
        [StringLength(40)]
        [Key]
        [Display(Name = "Product name")]
        public string ProductName { get; set; } // ProductName (Primary key) (length: 40)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UnitPrice", Order = 4, TypeName = "money")]
        [Required]
        [Key]
        [Display(Name = "Unit price")]
        public decimal UnitPrice { get; set; } // UnitPrice (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Quantity", Order = 5, TypeName = "smallint")]
        [Required]
        [Key]
        [Display(Name = "Quantity")]
        public short Quantity { get; set; } // Quantity (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Discount", Order = 6, TypeName = "real")]
        [Required]
        [Key]
        [Display(Name = "Discount")]
        public float Discount { get; set; } // Discount (Primary key)

        [Column(@"ExtendedPrice", Order = 7, TypeName = "money")]
        [Display(Name = "Extended price")]
        public decimal? ExtendedPrice { get; set; } // ExtendedPrice
    }

}
// </auto-generated>
