// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{

    // Orders Qry
    [Table("Orders Qry", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ViewOrdersQry /* Column Count = 20 */
    {
        // Number of columns for table ViewOrders Qry = 20
        public static int ColumnCount = 20;

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"OrderID", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Order ID")]
        public int OrderId { get; set; } // OrderID (Primary key)

        [Column(@"CustomerID", Order = 2, TypeName = "nchar")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Customer ID")]
        public string CustomerId { get; set; } // CustomerID (length: 5)

        [Column(@"EmployeeID", Order = 3, TypeName = "int")]
        [Display(Name = "Employee ID")]
        public int? EmployeeId { get; set; } // EmployeeID

        [Column(@"OrderDate", Order = 4, TypeName = "datetime")]
        [Display(Name = "Order date")]
        public System.DateTime? OrderDate { get; set; } // OrderDate

        [Column(@"RequiredDate", Order = 5, TypeName = "datetime")]
        [Display(Name = "Required date")]
        public System.DateTime? RequiredDate { get; set; } // RequiredDate

        [Column(@"ShippedDate", Order = 6, TypeName = "datetime")]
        [Display(Name = "Shipped date")]
        public System.DateTime? ShippedDate { get; set; } // ShippedDate

        [Column(@"ShipVia", Order = 7, TypeName = "int")]
        [Display(Name = "Ship via")]
        public int? ShipVia { get; set; } // ShipVia

        [Column(@"Freight", Order = 8, TypeName = "money")]
        [Display(Name = "Freight")]
        public decimal? Freight { get; set; } // Freight

        [Column(@"ShipName", Order = 9, TypeName = "nvarchar")]
        [MaxLength(40)]
        [StringLength(40)]
        [Display(Name = "Ship name")]
        public string ShipName { get; set; } // ShipName (length: 40)

        [Column(@"ShipAddress", Order = 10, TypeName = "nvarchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Ship address")]
        public string ShipAddress { get; set; } // ShipAddress (length: 60)

        [Column(@"ShipCity", Order = 11, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Ship city")]
        public string ShipCity { get; set; } // ShipCity (length: 15)

        [Column(@"ShipRegion", Order = 12, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Ship region")]
        public string ShipRegion { get; set; } // ShipRegion (length: 15)

        [Column(@"ShipPostalCode", Order = 13, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Ship postal code")]
        public string ShipPostalCode { get; set; } // ShipPostalCode (length: 10)

        [Column(@"ShipCountry", Order = 14, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Ship country")]
        public string ShipCountry { get; set; } // ShipCountry (length: 15)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CompanyName", Order = 15, TypeName = "nvarchar")]
        [Required]
        [MaxLength(40)]
        [StringLength(40)]
        [Key]
        [Display(Name = "Company name")]
        public string CompanyName { get; set; } // CompanyName (Primary key) (length: 40)

        [Column(@"Address", Order = 16, TypeName = "nvarchar")]
        [MaxLength(60)]
        [StringLength(60)]
        [Display(Name = "Address")]
        public string Address { get; set; } // Address (length: 60)

        [Column(@"City", Order = 17, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "City")]
        public string City { get; set; } // City (length: 15)

        [Column(@"Region", Order = 18, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Region")]
        public string Region { get; set; } // Region (length: 15)

        [Column(@"PostalCode", Order = 19, TypeName = "nvarchar")]
        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Postal code")]
        public string PostalCode { get; set; } // PostalCode (length: 10)

        [Column(@"Country", Order = 20, TypeName = "nvarchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Country")]
        public string Country { get; set; } // Country (length: 15)
    }

}
// </auto-generated>
