// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ConfigurationContext
{
    using Entities;
    using Interfaces;

    // Sales Totals by Amount
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class ViewSalesTotalsByAmountConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ViewSalesTotalsByAmount>
    {
        public ViewSalesTotalsByAmountConfiguration()
            : this("dbo")
        {
        }

        public ViewSalesTotalsByAmountConfiguration(string schema)
        {
            Property(x => x.SaleAmount).IsOptional().HasPrecision(19,4);
            Property(x => x.ShippedDate).IsOptional();
        }
    }

}
// </auto-generated>
